### ISSUE TITLE
Ну здарова 

### ISSUE THREAD

**Issue by focking** [GroveZ45/TFA-Custom-Base#1]
пешка Юры

**Comment by nightmatt23** [comment]
Ты как эту хуйню сделал

**Comment by focking** [comment]
В сумаcшедший дом приехала комиссия:
видит все с рулями бегают
пошли к главврачу и спрашивают его
-Почему у вас все с рулями бегают
Главврач достает руль и говорит
-Поехали, поглядим

**Comment by GroveZ45** [comment]
ПОЗАКРЫВАЛИ ПИЗДАКИ

**Comment by nightmatt23** [comment]
Едут в купе грузин, бабка и украинец. Украинец на верхней полке, снизу грузин, напротив грузина бабка. Едут из кацапурии в Украину. Едут долго и нудно. Украинцу стало скучно, он плюнул на грузина. Грузин вытирает плевок с лысины и спрашивает:
— Хто нахаркив, хто нахаркив?!
Бабка напротив:
— Я на Харків.
Грузин бьет бабку в табло. Едут дальше. История повторяется, украинец плюет грузину на голову, и грузин в панике:
— Хто нахаркив, хто нахаркив?!!!!
Баба тихо:
— Я синку на Харків. Бабка опять получает в бубен от грузина. Спустя некоторое время то же самое. Грузин:
— Хто нахаркив, хто нахаркив?!!!!
Бабка:
— Та ладно, я вже до Луганьску, а там пішочком.

> ПОЗАКРЫВАЛИ ПИЗДАКИ
